-- ═══════════════════════════════════════════════════════════
--  AllergyTrack – Supabase séma
--  Futtasd le a Supabase Dashboard → SQL Editor oldalon
-- ═══════════════════════════════════════════════════════════

-- ── profiles tábla ──────────────────────────────────────────
create table public.profiles (
  id              uuid references auth.users on delete cascade primary key,
  display_name    text,
  avatar_url      text,
  bio             text,
  allergen_profile jsonb default '[]'::jsonb,
  app_settings    jsonb default '{}'::jsonb,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

-- Row Level Security bekapcsolása
alter table public.profiles enable row level security;

-- Csak saját profil olvasható
create policy "Own profile select"
  on public.profiles for select
  using (auth.uid() = id);

-- Csak saját profil frissíthető
create policy "Own profile update"
  on public.profiles for update
  using (auth.uid() = id);

-- Csak saját profil szúrható be
create policy "Own profile insert"
  on public.profiles for insert
  with check (auth.uid() = id);

-- Automatikus profil létrehozás regisztrációkor
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data->>'display_name',
      split_part(new.email, '@', 1)
    )
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ── updated_at automatikus frissítése ───────────────────────
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

-- ═══════════════════════════════════════════════════════════
--  shared_pollen_data – KOLLEKTÍV (publikus) pollenadatok
--  • Bárki OLVASHATJA (bejelentkezés nélkül is)
--  • CSAK az admin fiók ÍRHATJA (feltöltés)
--  Idempotens: többször is lefuttatható.
--  Admin e-mail: wagnergaborwagner503@gmail.com
-- ═══════════════════════════════════════════════════════════
create table if not exists public.shared_pollen_data (
  id            bigint generated by default as identity primary key,
  date          date not null,
  location      text not null,
  allergen_id   text not null,
  concentration double precision,
  unit          text,
  risk_level    int  not null default 0,
  created_at    timestamptz default now(),
  updated_at    timestamptz default now()
);

-- Egyedi kulcs az upsert-hez (onConflict: date,location,allergen_id)
create unique index if not exists shared_pollen_unique
  on public.shared_pollen_data (date, location, allergen_id);

alter table public.shared_pollen_data enable row level security;

-- Publikus olvasás: anonim ÉS bejelentkezett felhasználók is
drop policy if exists "Public pollen read" on public.shared_pollen_data;
create policy "Public pollen read"
  on public.shared_pollen_data for select
  using (true);

-- Beszúrás CSAK az admin e-mailről (pont nélküli és pontos Gmail alak is)
drop policy if exists "Admin pollen insert" on public.shared_pollen_data;
create policy "Admin pollen insert"
  on public.shared_pollen_data for insert
  with check (
    lower(auth.jwt() ->> 'email') in (
      'wagnergaborwagner503@gmail.com',
      'wagnergaborwagner.503@gmail.com'
    )
  );

-- Frissítés CSAK az admin e-mailről
drop policy if exists "Admin pollen update" on public.shared_pollen_data;
create policy "Admin pollen update"
  on public.shared_pollen_data for update
  using (
    lower(auth.jwt() ->> 'email') in (
      'wagnergaborwagner503@gmail.com',
      'wagnergaborwagner.503@gmail.com'
    )
  );

-- updated_at automatikus frissítése a megosztott táblán is
drop trigger if exists shared_pollen_updated_at on public.shared_pollen_data;
create trigger shared_pollen_updated_at
  before update on public.shared_pollen_data
  for each row execute function public.set_updated_at();

-- ⚠️ Ha korábban létrehoztál egy szabályt, ami MINDEN bejelentkezett
--    felhasználónak engedte az írást, töröld azt, hogy tényleg csak az
--    admin tölthessen fel. Listázd a meglévő szabályokat:
--    select policyname from pg_policies where tablename = 'shared_pollen_data';
--    majd: drop policy "A_RÉGI_SZABÁLY_NEVE" on public.shared_pollen_data;
